meson: update libgit2-glib-1.0 dependency
Recent gitg code requires APIs from libgit2 >= 0.27.8

Update the version of the dependency so that meson fails to configure
the project if an older version is available.

Without this change project configuration succeeds, but then compilation
fails with the following errors, and the user might not know why:

-----------------------------------------------------------------------
../gitg/gitg-commit-action-create-patch.vala:134.4-134.12: error: The name `body' does not exist in the context of `Ggit.DiffFormatEmailOptions'
			opts.body = message.substring(pos + 2, message.length - (pos + 2));
			^^^^^^^^^
../gitg/gitg-dash-view.vala:350.6-350.21: error: The name `update' does not exist in the context of `Ggit.Submodule'
					submodule.update(true, null);
					^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 2 warning(s)
-----------------------------------------------------------------------